name: Terraform Format Check
on:
  pull_request:
    branches:
      - main
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Check Terraform format
        run: terraform fmt -check -recursive